### ISSUE TITLE
Text from old todo stays in input field

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#15]
It would be more practical for the user, if the input field would clear after they submit their todo.
![screen shot 2018-11-09 at 10 03 50](https://user-images.githubusercontent.com/26569161/48256254-f23fbc00-e406-11e8-9c2a-141c70e65747.png)

**Comment by Brymon** [comment]
Try form reset() method (👍 )

**Comment by zurda** [comment]
Nice catch! We fixed it, and it will soon be pushed
