### ISSUE TITLE
Size of todos and the position of the buttons

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#17]
As seen on the screenshot below: Depending on the length of todos, the <li> element changes it's size and the buttons move. Try to rethink your DOM structure and CSS , so you can position your buttons in a fixed place, so if a user wants to delete them all, they don't have to look for buttons all over the screen ;)

![screen shot 2018-11-09 at 10 09 33](https://user-images.githubusercontent.com/26569161/48256483-a6414700-e407-11e8-8d49-713b5561f4ea.png)

**Comment by Brymon** [comment]
Here also, the buttons are higher than the text line, so it looks a bit weird that last line of my todo has some whitespace on top..

**Comment by zurda** [comment]
Nice catch! This is fixed and will soon be pushed :)
