### ISSUE TITLE
Input field size

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#18]
As a user, i would like to see the entire text input of my long todo, so i can see if i made a spelling mistake
![screen shot 2018-11-09 at 10 13 17](https://user-images.githubusercontent.com/26569161/48256641-210a6200-e408-11e8-801b-161c94ecb1a7.png)

**Comment by zurda** [comment]
Thanks for the feedback! We've just fixed it, and we'll soon push it :)
