### ISSUE TITLE
The position of the input field

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#19]
After entering loads of todos, the input field is no longer visible, to i have to scroll to add another todo. Would it be better if the input field was always above the fold? Or perhaps the page could scroll down with the input fields? I suggest the first option (👍 )

![screen shot 2018-11-09 at 10 15 17](https://user-images.githubusercontent.com/26569161/48256735-70509280-e408-11e8-9b90-7f58e0059fbf.png)

**Comment by zurda** [comment]
Good point! We fixed it, and will soon push the branch
