### ISSUE TITLE
Great README 

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#21]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

Especially that you included the instructions how to run locally 💃

**Comment by lucyewright** [comment]
Agree, Read me is awesome, STRONG ICON GAME!

**Comment by BenNewman90** [comment]
100% agree ! 👍 👍 👍 🥇

**Comment by Oliversw** [comment]
😊
