### ISSUE TITLE
You have tests and they all pass! 

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#22]
Also your tests are nicely grouped together by function tested.
So proud 😊 

![screen shot 2018-11-09 at 10 26 36](https://user-images.githubusercontent.com/26569161/48257297-0afda100-e40a-11e8-95a6-39f0f311317d.png)

**Comment by lucyewright** [comment]
Really liked the grouping of your tests in jest!  Well done on tests!

**Comment by Brymon** [comment]
You have line 77 in logic.js untested, but it's totally not you're fault: 

if (typeof module !== "undefined") {
  module.exports = todoFunctions;
}

... so you should not worry about it at all! 

Again: i love your tests  ❤️
