### ISSUE TITLE
Simple clean dry code

### ISSUE THREAD

**Issue by Brymon** [fac-15/AwesomeTodo#32]
`elementDone.done = !elementDone.done;`

I know that different groups struggled with making this function (markTodo) work, but looks like you guys smashed it! 

🏆

**Comment by Brymon** [comment]
`elementDone = todoCopy.find(function(ele) {
      return ele.id === idToMark};`

here also in your markTodo function, one small comment: 
from the context i know that (ele) is element, but generally people use (el) for element, not a big deal at all though!

**Comment by zurda** [comment]
Thanks @Brymon ! We might switch `ele` to `el` - we didn't know about the convention. We appreciate the tip!
