### ISSUE TITLE
Input submit button

### ISSUE THREAD

**Issue by lucyewright** [fac-15/AwesomeTodo#34]
You can add an empty item to the list...
<img width="437" alt="screenshot 2018-11-09 at 10 42 03" src="https://user-images.githubusercontent.com/40594944/48258059-210c6100-e40c-11e8-8267-163ff7b4aaa3.png">

**Comment by zurda** [comment]
Nice catch @lucyewright ! We'll do our best to get this fixed today :) Hopefully, we'll have time, but definitely a stretch goal
